### ISSUE TITLE
Организация файлов контрактов

### ISSUE THREAD

**Issue by dzarezenko** [LoborchukAndrii/MyElephant#2]
https://github.com/LoborchukAndrii/MyElephant/blob/706c9923a58bd53b5a3d726d7d93877fdfbd255d/ManyOwners/contracts/Migrations.sol#L115

**Comment by dzarezenko** [comment]
Использовать `Migrations.sol` как единственный файл контракта в корне не верно!
Все отдельные контракты, библиотеки и интерфейсы необходимо разносить в отдельные `.sol` файлы и использовать директиву `import`.

**Comment by LoborchukAndrii** [comment]
Добре, виправлю.
